### ISSUE TITLE
Bug: Does not work in Tests

### ISSUE THREAD

**Issue by Vaibhav2002** [jordond/connectivity#59]
If i am creating `Connectivity` in tests, it fails to instantiate with this error

```
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'dev.jordond.connectivity.Connectivity']'
	at app//org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:57)
	at app//org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
	at app//org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:55)
	at app//org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
	at app//org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:36)
	at app//org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:53)
	at app//org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:109)
	at app//org.koin.core.scope.Scope.resolveValue(Scope.kt:247)
	at app//org.koin.core.scope.Scope.resolveInstance(Scope.kt:233)
	at app//org.koin.core.scope.Scope.get(Scope.kt:212)
	at app//com.medial.app.core.di.CoreModuleKt$_get_coreModule_$lambda$3$$inlined$singleOf$default$1.invoke(SingleOf.kt:227)
	at app//com.medial.app.core.di.CoreModuleKt$_get_coreModule_$lambda$3$$inlined$singleOf$default$1.invoke(SingleOf.kt:52)
	at app//org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
	... 161 more
Caused by: java.lang.IllegalStateException: ContextProvider has not been initialized
	at dev.jordond.connectivity.tools.ContextProvider$Companion.getInstance(ContextProvider.kt:39)
	at dev.jordond.connectivity.AndroidConnectivityKt.Connectivity(AndroidConnectivity.kt:21)
	at dev.jordond.connectivity.AndroidConnectivityKt.AndroidConnectivity(AndroidConnectivity.kt:38)
	at dev.jordond.connectivity.MobileConnectivity_androidKt.Connectivity(MobileConnectivity.android.kt:17)
	at dev.jordond.connectivity.MobileConnectivity_androidKt.Connectivity$default(MobileConnectivity.android.kt:14)
	at com.medial.app.core.di.CoreModuleKt._get_coreModule_$lambda$3$lambda$1(CoreModule.kt:23)
	at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
	... 173 more

```

Please provide a test version of this, so I can use in unit tests

**Comment by jhabaa** [comment]
Hi, any solution ?

**Comment by jordond** [comment]
`Connectivity` is [exposed](https://github.com/jordond/connectivity/blob/56c4ea4c3719d9bc055dafe66f994b2ecc6f91c6/connectivity-core/src/commonMain/kotlin/dev/jordond/connectivity/Connectivity.kt) as an `interface`. So you can provide a fake implementation when running your tests.

One isn't currently included, and I can certainly add one. But it is pretty trivial to implement a basic fake for tests.

**Comment by jordond** [comment]
Still on my list.

For anyone hitting this now, the immediate fix is to not construct the real `Connectivity` in unit tests, inject the `Connectivity` interface and hand your test a fake implementation. The crash itself is because the Android artifact gets its `Context` from an androidx.startup initializer, which doesn't run in JVM unit tests.

I want to ship a proper test fake artifact for this. The cold flow API in #264 also makes this a lot easier to fake since it's just a `Flow`.
